### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by dustin-graham** [auth0/JWTDecode.Android#22]
Hello, I ran into a problem using this library with out Auth0 implementation. I believe the work around would be pretty easy and I wouldn't mind contributing to this project with a pull request. However, I'm having trouble building the project locally as it seems to rely on a plugin that is only available in a private Bintray repo. Do you have any sort of contribution guide?

Specifically, what I'm trying to do is related to #21 . We're sending some custom JSON in our tokens and I need to get them out. none of the ClaimImpl methods work for me. I was thinking that if I could simply get out the raw value from the `Claim` that I could handle parsing the JSON myself.

**Comment by lbalmaceda** [comment]
We don't support deep structures, only plain first level objects. We don't plan to add support to this either. The content of the payload in the token should be simple enough for you to display the basic information on a View or perform the required calls to your API. I don't know your particular use case but storing things such as a full user profile is not a good practice, and we try to discourage that.

To answer your original question there's no contribution guide. Just fork the repo, do the changes and open a PR. It will be reviewed and eventually merged. 🎉 You shouldn't run into any dependency issue since all of them are hosted in public repos. 


Feel free to open a new issue if you run into a different problem.
