### ISSUE TITLE
JWT encode for Android?

### ISSUE THREAD

**Issue by scbabacus-midnight** [auth0/JWTDecode.Android#59]
Someone mentioned that JWT signing on clients does not make much sense because you can't keep the shared secret secret.

I still don't get the complete picture why.
Supposed I have a login screen for my user on a mobile app, and I negotiate the shared secret between clients and servers on each login. I can keep the shared secret in, says, secured storage of the device, can't I?

I don't see which part of it is not feasible.
Can someone explain the lack of an encoding library for mobile devices?
May I add it as a feature request?

**Comment by lbalmaceda** [comment]
>you can't keep the shared secret, secret.

That assumes that you are using a symmetric signing schema, for example, using the `client_secret` from your Authorization Server's client. For which you'd have to hardcode or include that secret in the app, which anyone can decompile and obtain because in the end is plaintext. You can make it harder by doing some byte manipulation, but that can still be reversed by an attacker.

>  I negotiate the shared secret between clients and servers on each login- I can keep the shared secret in the secure storage of the device

I guess if the connection is secure and encrypted somehow, it could be safe to obtain a secret that way, yes. But I'm not sure that you're still covered from man-in-the-middle attacks. Or, if you were able to negotiate the secret with the server, what prevents other apps from doing that as well on your behalf?

Then, how you store that securely is another challenge, especially in terms of UX. You could find a database with encryption support and ask the user to generate a password that you don't store anywhere, for example, but that you use to unlock the database. But when the user forgets the password, you'd need to think of a strategy for them to be able to recover their data (or not).


In the end, what benefit do you see in signing [JWTs](http://jwt.io/) from each client instead of doing that in the server? Can you expand on the use case and what you're trying to achieve?

Cheers

**Comment by scbabacus-midnight** [comment]
> I guess if the connection is secure and encrypted somehow, it could be safe to obtain a secret that way, yes. But I'm not sure that you're still covered from man-in-the-middle attacks. Or, if you were able to negotiate the secret with the server, what prevents other apps from doing that as well on your behalf?

Other apps sure can, but with the user-supplied password, which is out of my app responsibility. MITM is unlikely because, of course, over TLS.

> In the end, what benefit do you see in signing [JWTs](http://jwt.io/) from each client instead of doing that in the server? Can you expand on the use case and what you're trying to achieve?

The use case is for API request encoding.
JWT has a lot of common features standardized already,
e.g., iat, iss, aud claims, and kid header is some neat ones.

Most of the code is there in many languages, making JWT an attractive way to encode API requests with lots of ready-made functionalities.  
I don't plan to do some fancy stuff, just bland HMAC signing; the secret can be negotiated over HTTPS. The objective of the secret is to prevent other devices from claiming the credential, more like using it as some kind of long-term session cookie.

**Comment by scbabacus-midnight** [comment]
Fair enough, thanks.
